# Generated by Django 5.2.3 on 2025-07-07 10:32

import auth_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', auth_app.models.CustomUserManager()),
            ],
        ),
    ]
