# Generated by Django 5.2.3 on 2025-06-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offerdetail_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
    ]
